"""
dashboard/app.py
-----------------
Interactive dashboard for the customer lifecycle funnel and the
Control / Variant_A / Variant_B experiment.

Runs in one of two modes, chosen automatically:

  * LIVE mode -- if data/processed/warehouse.db exists (i.e. you've
    downloaded the real dataset and run `python -m src.pipeline`
    locally), the dashboard queries it directly.

  * DEMO mode -- otherwise (e.g. a Streamlit Community Cloud deployment,
    where the real ~200MB licensed dataset isn't bundled), it falls back
    to the small precomputed result files in dashboard/demo_data/,
    generated by `python -m src.export_demo_data` from a real run. A
    banner makes clear which mode is active.

Run:
    streamlit run dashboard/app.py
"""

import json
import os
import sys

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEMO_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "demo_data")
WAREHOUSE_PATH = os.path.join(ROOT_DIR, "data", "processed", "warehouse.db")
sys.path.insert(0, ROOT_DIR)

LIVE_MODE = os.path.exists(WAREHOUSE_PATH)

GROUPS = ["Control", "Variant_A", "Variant_B"]


def format_p(p: float) -> str:
    return "< 0.0001" if p < 0.0001 else f"{p:.4g}"


if LIVE_MODE:
    from src.ab_testing import _load_customer_group_counts, chi_square_test, group_totals, pairwise_tests
    from src.funnel_analysis import (
        bounce_rate, customer_step_reach, funnel_by_channel, overall_funnel, revenue_per_converted_customer,
    )

    reach = customer_step_reach()
    overall = overall_funnel(reach)
    by_channel = funnel_by_channel(reach)

    counts = _load_customer_group_counts()
    totals = group_totals(counts)
    chi2_stat, chi2_p, chi2_dof = (lambda r: (r["chi2"], r["p_value"], r["dof"]))(chi_square_test(counts))
    pairwise_rows = [
        {"group_a": r.group_a, "group_b": r.group_b, "absolute_lift_pp": r.absolute_lift_pp,
         "p_value": r.p_value, "significant": r.significant}
        for r in pairwise_tests(counts)
    ]
    bounce = bounce_rate()
    avg_revenue = revenue_per_converted_customer()

else:
    overall = pd.read_csv(os.path.join(DEMO_DATA_DIR, "funnel_overall.csv"))
    by_channel = pd.read_csv(os.path.join(DEMO_DATA_DIR, "funnel_by_channel.csv"))
    by_channel["step_name"] = pd.Categorical(
        by_channel["step_name"], categories=["view", "click", "add_to_cart", "purchase"], ordered=True
    )

    totals = pd.read_csv(os.path.join(DEMO_DATA_DIR, "ab_test_totals.csv")).set_index("experiment_group")

    with open(os.path.join(DEMO_DATA_DIR, "ab_test_pairwise.json")) as f:
        pairwise_rows = json.load(f)

    with open(os.path.join(DEMO_DATA_DIR, "summary_stats.json")) as f:
        summary = json.load(f)
    chi2_stat, chi2_p, chi2_dof = summary["chi2"], summary["chi2_p_value"], summary["chi2_dof"]
    bounce = summary["bounce_rate_pct"]
    avg_revenue = summary["avg_revenue_per_converted_customer"]


st.set_page_config(page_title="Marketing Funnel & Experiment Analytics", layout="wide")

st.title("Marketing & E-Commerce Funnel Analytics")
st.caption(
    "Built on the real Kaggle 'Marketing & E-Commerce Analytics Dataset' "
    "(Geetha Sagar Bonthu, CC0) -- see data/README.md for source & citation."
)

if not LIVE_MODE:
    st.info(
        "**Demo mode** -- showing precomputed results from a real run against "
        "the full dataset. The dataset itself (~200MB, CC0-licensed but not "
        "bundled here) isn't present in this environment. Clone the repo and "
        "follow `data/README.md` to run this dashboard live against it.",
        icon="ℹ️",
    )

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total customers", f"{overall.loc[0, 'customers_reached']:,}")
col2.metric("Ever purchased", f"{overall.loc[len(overall)-1, 'customers_reached']:,}",
            f"{overall.loc[len(overall)-1, 'pct_of_customers']}% of customers")
worst_row = overall.iloc[1:].sort_values("drop_off_pct", ascending=False).iloc[0]
col3.metric("Biggest drop-off stage", worst_row["step_name"], f"-{worst_row['drop_off_pct']}%")
col4.metric("Avg. revenue / converted customer", f"${avg_revenue:,.2f}")

st.subheader("Customer lifecycle funnel")
st.caption(
    "Not a per-visit funnel -- the source data has no recoverable session "
    "structure (median 36-day gap between a customer's events), so this "
    "tracks whether a customer EVER reached each stage. See data/README.md."
)
fig_funnel = go.Figure(go.Funnel(
    y=overall["step_name"],
    x=overall["customers_reached"],
    textinfo="value+percent initial",
))
st.plotly_chart(fig_funnel, use_container_width=True)
st.caption(f"Bounce rate (share of all events that are 'bounce'): {bounce}%")

st.subheader("Ever-purchased rate by acquisition channel")
purchased_by_channel = by_channel[by_channel["step_name"] == "purchase"].sort_values(
    "pct_of_signups", ascending=False
)
fig_channel = px.bar(
    purchased_by_channel, x="pct_of_signups", y="acquisition_channel",
    orientation="h", labels={"pct_of_signups": "% of customers who ever purchased", "acquisition_channel": "Channel"},
)
st.plotly_chart(fig_channel, use_container_width=True)

st.subheader("Experiment: Control vs. Variant_A vs. Variant_B")
st.caption(
    "experiment_group is assigned per-event, not persisted per customer -- "
    "tested at the event level with a customer-clustered bootstrap as a "
    "robustness check. See src/ab_testing.py for the full treatment."
)

c1, c2, c3 = st.columns(3)
for col, group in zip([c1, c2, c3], GROUPS):
    col.metric(group, f"{totals.loc[group, 'purchase_rate']:.2%}",
               f"n={int(totals.loc[group, 'total_events']):,} events")

st.caption(f"3-group chi-square: χ²={chi2_stat:.1f}, p={format_p(chi2_p)}, dof={chi2_dof}")

pairwise_df = pd.DataFrame([
    {
        "Comparison": f"{r['group_a']} vs {r['group_b']}",
        "Lift (pp)": round(r["absolute_lift_pp"], 2),
        "p-value": format_p(r["p_value"]),
        "Significant (Bonferroni)": "Yes" if r["significant"] else "No",
    }
    for r in pairwise_rows
])
st.dataframe(pairwise_df, use_container_width=True, hide_index=True)

st.subheader("Funnel detail table")
st.dataframe(overall, use_container_width=True, hide_index=True)
